version: "2"

networks:
  app-tier:
    driver: bridge

services:
  rabbitmq:
    image: "bitnami/rabbitmq:latest"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
    networks:
      - app-tier
