version: "2"

networks:
  app-tier:
    driver: bridge

services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: spotter-library
    environment:
      - SPOTTER_AMQP_USERNAME=user
      - SPOTTER_AMQP_PASSWORD=password
      - SPOTTER_AMQP_HOST=rabbitmq
      - SPOTTER_AMQP_PORT=5672
    volumes:
      - ./:/app/
    depends_on:
      - rabbitmq
    networks:
      - app-tier
    tty: true

  rabbitmq:
    image: "bitnami/rabbitmq:latest"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
    networks:
      - app-tier
